export const ALL_COUNTRIES = 'ALL_COUNTRIES';
export const COUNTRY_BY_ID = 'COUNTRY_BY_ID';
export const NEW_ACTIVITY = 'NEW_ACTIVITY';
export const ACTIVITIES_BY_COUNTRY_ID = 'ACTIVITIES_BY_COUNTRY_ID';
export const COUNTRIES_SEARCH = 'COUNTRIES_SEARCH';